"""
vn_symbols.py – Danh sách mã chứng khoán Việt Nam (HOSE / HNX / UPCOM)
Dùng cho autocomplete tìm kiếm trên frontend.
"""

# Danh sách các mã phổ biến + tên công ty (không phải toàn bộ – các mã không có
# trong danh sách này vẫn tra cứu được, chỉ là không có gợi ý tên công ty).
VN_STOCKS = [
    # ─── Ngân hàng ────────────────────────────────────────────────────────────
    ("VCB", "Vietcombank"),
    ("BID", "BIDV"),
    ("CTG", "VietinBank"),
    ("TCB", "Techcombank"),
    ("MBB", "MB Bank"),
    ("VPB", "VPBank"),
    ("ACB", "ACB"),
    ("STB", "Sacombank"),
    ("HDB", "HDBank"),
    ("TPB", "TPBank"),
    ("SHB", "SHB"),
    ("EIB", "Eximbank"),
    ("OCB", "OCB"),
    ("MSB", "MSB"),
    ("LPB", "LPBank"),
    ("VIB", "VIB"),
    ("SSB", "SeABank"),
    ("BAB", "BacABank"),
    ("BVB", "BaoVietBank"),
    ("ABB", "ABBank"),
    ("NAB", "NamABank"),
    ("PGB", "PGBank"),
    ("VAB", "VietABank"),
    ("KLB", "Kienlongbank"),

    # ─── Bất động sản & Xây dựng ─────────────────────────────────────────────
    ("VIC", "Vingroup"),
    ("VHM", "Vinhomes"),
    ("VRE", "Vincom Retail"),
    ("NVL", "Novaland"),
    ("KDH", "Khang Điền"),
    ("NLG", "Nam Long"),
    ("DXG", "Đất Xanh"),
    ("PDR", "Phát Đạt"),
    ("DIG", "DIC Corp"),
    ("HDG", "Hà Đô"),
    ("CEO", "CEO Group"),
    ("KBC", "Kinh Bắc"),
    ("ITA", "Tân Tạo"),
    ("HQC", "Hoàng Quân"),
    ("LDG", "LDG"),
    ("AGG", "An Gia"),
    ("NTL", "Đô Thị Từ Liêm"),
    ("SCR", "Sài Gòn Thương Tín BĐS"),
    ("CRE", "Cen Land"),
    ("TCH", "Hoàng Huy"),
    ("HHV", "Đèo Cả"),
    ("VCG", "Vinaconex"),
    ("HBC", "Hòa Bình"),
    ("CTD", "Coteccons"),
    ("FCN", "Fecon"),
    ("LCG", "Licogi 16"),
    ("BCG", "Bamboo Capital"),
    ("DPG", "Đạt Phương"),
    ("PHC", "Phục Hưng Holdings"),
    ("ROS", "FLC Faros"),
    ("FLC", "FLC Group"),
    ("HAR", "An Dương Thảo Điền"),
    ("QCG", "Quốc Cường Gia Lai"),
    ("TDH", "Thủ Đức House"),
    ("HDC", "Hodeco"),
    ("SJS", "Sông Đà Sudico"),

    # ─── Khu công nghiệp ─────────────────────────────────────────────────────
    ("BCM", "Becamex IDC"),
    ("IDC", "IDICO"),
    ("SZC", "Sonadezi Châu Đức"),
    ("SIP", "Sài Gòn VRG"),
    ("LHG", "Long Hậu"),
    ("ITC", "Intresco"),
    ("VGC", "Viglacera"),
    ("NTC", "Nam Tân Uyên"),

    # ─── Thép & Vật liệu ─────────────────────────────────────────────────────
    ("HPG", "Hòa Phát"),
    ("HSG", "Hoa Sen"),
    ("NKG", "Nam Kim"),
    ("TLH", "Tiến Lên"),
    ("POM", "Pomina"),
    ("SMC", "SMC Trading"),
    ("VGS", "Vingal"),
    ("KSB", "Khoáng Sản Bình Dương"),
    ("HT1", "Xi măng Hà Tiên"),
    ("BCC", "Xi măng Bỉm Sơn"),
    ("BMP", "Nhựa Bình Minh"),
    ("NTP", "Nhựa Tiền Phong"),
    ("AAA", "An Phát Bioplastics"),

    # ─── Dầu khí & Năng lượng ────────────────────────────────────────────────
    ("GAS", "PV Gas"),
    ("PLX", "Petrolimex"),
    ("BSR", "Lọc Hóa Dầu Bình Sơn"),
    ("PVS", "PTSC"),
    ("PVD", "PV Drilling"),
    ("PVC", "PVChem"),
    ("PVT", "PVTrans"),
    ("OIL", "PV OIL"),
    ("POW", "PV Power"),
    ("NT2", "Nhơn Trạch 2"),
    ("REE", "REE Corp"),
    ("GEX", "Gelex"),
    ("HDG", "Hà Đô"),
    ("PC1", "PC1 Group"),
    ("VSH", "Vĩnh Sơn Sông Hinh"),
    ("HND", "Hải Phòng Power"),

    # ─── Bán lẻ & Hàng tiêu dùng ─────────────────────────────────────────────
    ("MWG", "Thế Giới Di Động"),
    ("FRT", "FPT Retail"),
    ("PNJ", "PNJ"),
    ("DGW", "Digiworld"),
    ("PET", "Petrosetco"),
    ("MSN", "Masan Group"),
    ("MCH", "Masan Consumer"),
    ("MML", "Masan MeatLife"),
    ("VNM", "Vinamilk"),
    ("SAB", "Sabeco"),
    ("BHN", "Habeco"),
    ("KDC", "KIDO Group"),
    ("VHC", "Vĩnh Hoàn"),
    ("ANV", "Nam Việt"),
    ("IDI", "IDI Corp"),
    ("FMC", "Sao Ta"),
    ("CMX", "Camimex"),
    ("ACL", "Cửu Long"),

    # ─── Phân bón & Hóa chất ─────────────────────────────────────────────────
    ("DGC", "Hóa chất Đức Giang"),
    ("DCM", "Đạm Cà Mau"),
    ("DPM", "Đạm Phú Mỹ"),
    ("LAS", "Supe Lâm Thao"),
    ("CSV", "Hóa chất Cơ Bản Miền Nam"),
    ("DDV", "DAP-Vinachem"),

    # ─── Vận tải, Logistics ──────────────────────────────────────────────────
    ("ACV", "ACV"),
    ("HVN", "Vietnam Airlines"),
    ("VJC", "VietJet Air"),
    ("GMD", "Gemadept"),
    ("VOS", "Vận tải Biển VN"),
    ("VSC", "Container Việt Nam"),
    ("HAH", "Hải An"),
    ("STG", "Sotrans"),
    ("PHP", "Cảng Hải Phòng"),
    ("PVP", "Vận tải Dầu khí"),

    # ─── Công nghệ & Viễn thông ──────────────────────────────────────────────
    ("FPT", "FPT Corp"),
    ("CMG", "CMC Corp"),
    ("ELC", "ELCOM"),
    ("VGI", "Viettel Global"),
    ("CTR", "Viettel Construction"),
    ("VTP", "Viettel Post"),
    ("MFS", "Mobifone Service"),

    # ─── Chứng khoán ─────────────────────────────────────────────────────────
    ("SSI", "SSI Securities"),
    ("VND", "VNDirect"),
    ("VCI", "Bản Việt Securities"),
    ("HCM", "HSC"),
    ("SHS", "SHS"),
    ("MBS", "MB Securities"),
    ("VIX", "VIX Securities"),
    ("CTS", "VietinBank Securities"),
    ("BSI", "BIDV Securities"),
    ("FTS", "FPTS"),
    ("AGR", "Agriseco"),
    ("BVS", "BVSC"),
    ("ORS", "ORS"),
    ("APG", "APG Securities"),
    ("PSI", "PSI"),
    ("VFS", "VFS"),

    # ─── Bảo hiểm ────────────────────────────────────────────────────────────
    ("BVH", "Bảo Việt Holdings"),
    ("BIC", "BIC"),
    ("BMI", "Bảo Minh"),
    ("MIG", "MIC"),
    ("PVI", "PVI"),
    ("PGI", "PJICO"),
    ("VNR", "Vinare"),

    # ─── Y tế, Dược phẩm ─────────────────────────────────────────────────────
    ("DHG", "Dược Hậu Giang"),
    ("IMP", "Imexpharm"),
    ("DBD", "Bidiphar"),
    ("TRA", "Traphaco"),
    ("DMC", "Domesco"),
    ("DVN", "Vimedimex"),
    ("DBT", "Bến Tre Pharma"),

    # ─── Cao su, Nông nghiệp ─────────────────────────────────────────────────
    ("GVR", "VRG"),
    ("DPR", "Cao su Đồng Phú"),
    ("PHR", "Cao su Phước Hòa"),
    ("TRC", "Cao su Tây Ninh"),
    ("HAG", "HAGL"),
    ("HNG", "HAGL Agrico"),
    ("BAF", "BAF Việt Nam"),
    ("DBC", "Dabaco"),
    ("HAX", "Haxaco"),

    # ─── Khác ────────────────────────────────────────────────────────────────
    ("GEG", "Gia Lai Electricity"),
    ("LHC", "Đầu tư & Xây dựng Thủy Lợi"),
    ("TNG", "TNG"),
    ("MSH", "May Sông Hồng"),
    ("TCM", "Dệt Thành Công"),
    ("STK", "Sợi Thế Kỷ"),
    ("VGT", "Vinatex"),
    ("PAN", "PAN Group"),
    ("LTG", "Lộc Trời"),
    ("SBT", "Thành Thành Công"),
    ("QNS", "Đường Quảng Ngãi"),
]
